# Generated by Django 4.2.5 on 2023-09-30 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0008_husband_women_husband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'verbose_name': 'Знаменитые женщины'},
        ),
        migrations.AddField(
            model_name='tagposts',
            name='m_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='women',
            name='husband',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='women', to='women.husband'),
        ),
    ]
